- name: "Hosts"
  hosts: all
  become: yes

  tasks:

   - name: "Docker | kubernetes create cluster [init]"
     command: kubeadm init
     register: kubeadm
     failed_when: "'FAILED' in swarm.stderr"
     ignore_errors: True

   - debug: msg="{{ kubeadm.stdout }}"

   - name: "Docker | Create directory kubernetes"
     file: path=/home/ubuntu/.kube state=directory mode=0755

   - name: "Docker | Kubernetes copy config"
     shell: |
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config